[package]
name = "fuzzy-json"
version = "0.1.0"
edition = "2021"

license = "MIT"
description = "Fuzzy JSON parser"
homepage = "https://github.com/cympfh/fuzzy-json-rs"

[dependencies]
nom = "7"
structopt = { version = "0.3", default-features = false }

[[bin]]
name = "fson"
